### PR TITLE
fix: Polymer element properties in the prototype

### LINKED ISSUE #1: Properties are mapped to web component attributes

### PR DESCRIPTION
**Pull request by platosha**
Fixes #1

### CODE REVIEW

File: src/create-component.ts [hunk 1]
```diff
@@ -0,0 +1,12 @@
+import { createComponent as createComponentOriginal, EventName } from '@lit-labs/react';
+
+export function createComponent(...args: Parameters<typeof createComponentOriginal>) {
+  // TODO: improve or remove the Polymer workaround
+  // 'createComponent' relies on key presence on the custom element class, but
+  // Polymer defines properties on the prototype when the first element
+  // is created. Workaround, create a throw-away element to make the prototype
+  // reliable for 'createComponent'.
+  const [, tagName] = args;
+  document.createElement(tagName);
```
Comment (tomivirkki) [inline src/create-component.ts:10]: The set of properties can be read from `polymerElementClass._properties` even before the first element instance is created. For example:

```ts
const elementClass = args[2];
const mock = class {} as typeof elementClass;
Object.assign(mock.prototype, (elementClass as any)._properties);
args[2] = mock;
```

Comment (platosha) [reply src/create-component.ts]: Thanks for the tip!

**Review by Lodin — APPROVED** [review]
