### PR TITLE
fix(Select): enforce content update after render

### LINKED ISSUE #148: Select is not showing its value when using a renderer
```
<Select
          renderer={() => (
            <ListBox>
              <Item value="foo" {...{ label: "foo" }}>
                It is foo
              </Item>
              <Item value="bar" {...{ label: "bar" }}>
                It is bar
              </Item>
            </ListBox>
          )}
          value="foo"
        ></Select>
```

The select should show "foo" on the first render. It is instead rendered as empty.

This works properly in the web component, e.g.
```
s = document.createElement("vaadin-select");
s.value="foo";
s.renderer = (e) => e.innerHTML=`<vaadin-list-box>
              <vaadin-item value="foo" label="foo"}>
                It is foo
              </vaadin-item>
              <vaadin-item value="bar" label="bar">
                It is bar
              </vaadin-item>
            </vaadin-list-box>`;
document.body.append(s);
```

### PR DESCRIPTION
**Pull request by Lodin**
Fixes #148.

Also this PR simplifies the testing approach (only for `Select` component) to avoid weird failures.

### CODE REVIEW

File: src/Select.tsx [hunk 1]
```diff
@@ -14,10 +23,16 @@ export type SelectProps = Partial<Omit<_SelectProps, 'children' | 'renderer'>> &
   }>;
 
 function Select(props: SelectProps, ref: ForwardedRef<SelectElement>): ReactElement | null {
+  const innerRef = useRef<SelectElement>(null);
   const [portals, renderer] = useSimpleOrChildrenRenderer(props.renderer, props.children);
+  const finalRef = useMergedRefs(innerRef, ref);
+
+  useEffect(() => {
+    innerRef.current?.requestContentUpdate();
```
Comment (vursen) [inline src/Select.tsx:31]: I think it should only request a content update when a renderer is provided. When items API is used, everything already works correctly.

Comment (Lodin) [reply src/Select.tsx:31]: Oh, right, I forgot about that point

File: src/Select.tsx [hunk 2]
```diff
@@ -14,10 +23,18 @@ export type SelectProps = Partial<Omit<_SelectProps, 'children' | 'renderer'>> &
   }>;
 
 function Select(props: SelectProps, ref: ForwardedRef<SelectElement>): ReactElement | null {
+  const innerRef = useRef<SelectElement>(null);
   const [portals, renderer] = useSimpleOrChildrenRenderer(props.renderer, props.children);
+  const finalRef = useMergedRefs(innerRef, ref);
+
+  useEffect(() => {
+    if (props.renderer) {
+      innerRef.current?.requestContentUpdate();
```
Comment (vursen) [inline src/Select.tsx:32]: Does this approach work when setting a new renderer?

**Comment by Lodin** [comment]
@vursen, is this expression expected to work?
```tsx
render(<Select renderer={Renderer} value="bar" />);
expect(document.querySelector('vaadin-select-value-button')).to.have.text('Bar');

render(<Select renderer={Renderer} value="foo" />);
expect(document.querySelector('vaadin-select-value-button')).to.have.text('Foo');
```

**Comment by vursen** [comment]
> is this expression expected to work?

I believe so, unless React renders this asynchronosly.

File: src/Select.tsx [hunk 3]
```diff
@@ -14,10 +23,18 @@ export type SelectProps = Partial<Omit<_SelectProps, 'children' | 'renderer'>> &
   }>;
 
 function Select(props: SelectProps, ref: ForwardedRef<SelectElement>): ReactElement | null {
+  const innerRef = useRef<SelectElement>(null);
```
Comment (vursen) [inline src/Select.tsx:26]: Could we reuse the ref that is passed down to this component?

File: test/Select.spec.tsx [hunk 4]
```diff
@@ -31,47 +27,62 @@ describe('Select', () => {
...
   });
 
   it('should use renderer prop if it is set', async () => {
-    const { container } = render(<Select ref={ref} items={items} renderer={Renderer} value="bar" />);
-    await assert(container);
+    render(<Select renderer={Renderer} value="bar" />);
+    await assert(user);
   });
 
   it('should use children render function as a renderer prop', async () => {
```
Comment (vursen) [inline test/Select.spec.tsx:58]: I think it would be good to also have a test verifying that the value is set correctly when the `renderer` function is passed through `children`.

File: src/Select.tsx (hunk 3 above)
Comment (Lodin) [reply src/Select.tsx:26]: Unfortunately, no, because we have no idea if the user provided a function or a `MutableRefObject`.

File: test/Select.spec.tsx [hunk 5]
```diff
@@ -31,47 +27,73 @@ describe('Select', () => {
...
+    it('should correctly render the value if renderer prop is changed', async () => {
+      render(<Select renderer={Renderer} value="bar" />);
+      await findByQuerySelector('vaadin-select-value-button');
+
+      render(<Select renderer={NewRenderer} value="bar" />);
+
+      await expect(findByQuerySelector('vaadin-select-value-button')).to.eventually.have.text('Bar');
+    });
+
+    it('should correctly render the value if renderer prop is changed', async () => {
```
Comment (vursen) [inline test/Select.spec.tsx:91]:
```suggestion
    it('should correctly render the value if children prop is changed', async () => {
```

File: package.json [hunk 6]
```diff
@@ -534,6 +537,8 @@
     "./RichTextEditor": "./RichTextEditor.js",
     "./Scroller": "./Scroller.js",
     "./Select": "./Select.js",
+    "./SideNav": "./SideNav.js",
+    "./SideNavItem": "./SideNavItem.js",
```
Comment (vursen) [inline package.json:541]: Was it intentionally included in this PR? Doesn't look like a related change.

Comment (Lodin) [reply package.json:541]: 🤔

Comment (Lodin) [reply package.json:541]: I guess, it was done by a script, because we already have `SideNav` on line 421, but no supporting export on 538. I would suggest to leave it here because we would need to include it here anyway (and probably it's gonna be generated on each script run).

**Review by vursen — APPROVED** [review]
