### PR TITLE
fix!: exports cleanup

### LINKED ISSUE #37: Exports cleanup
- Using `-Module` prefix makes IDE suggestions list Modules and React components together.

- Package index import paths are preferred by IDE, but have worse performance in Vite because of loading the entire set of components.

Let us change the named export to `WebComponentModule` for every component and remove the package index exports.

### PR DESCRIPTION
**Pull request by platosha**
Fixes #37

### CODE REVIEW

File: scripts/generator.ts [hunk 1]
```diff
@@ -351,28 +351,13 @@ export { ${COMPONENT_NAME}Module };
...
 
-const indexFile = generateIndexFile(sourceFiles);
-
 async function printAndWrite(file: SourceFile) {
   const contents = printer.printFile(file);
   await writeFile(file.fileName, contents, 'utf8');
 }
 
-await Promise.all([...sourceFiles.map(printAndWrite), printAndWrite(indexFile)]);
+await Promise.all([...sourceFiles.map(printAndWrite)]);
```
Comment (Lodin) [inline scripts/generator.ts:363]: We don't need array spreading here

**Review by Lodin — CHANGES_REQUESTED** [review]

**Review by Lodin — APPROVED** [review]
