### PR TITLE
fix: update typings to avoid theme property deprecation

### LINKED ISSUE #32: Undeprecate "theme" property
The `theme` property is marked as deprecated in web components, however using the attribute should be allowed.

Currently it is confusingly deprecated for React wrappers. It should be safe to keep `theme` prop supported without deprecation, as the property support removal from the component would not make any impact for React users.

### PR DESCRIPTION
**Pull request by Lodin**
Fixes #32

### CODE REVIEW

File: test/kitchen-sink/Row1.tsx [hunk 1]
```diff
@@ -8,7 +8,7 @@ import { ChartSeries } from '../../src/ChartSeries.js';
 export default function Row1() {
   return (
     <BoardRow>
-      <Accordion>
+      <Accordion theme="primary">
```
Comment (platosha) [inline test/kitchen-sink/Row1.tsx:11]: Could a test assert that the attribute is in the DOM?

**Review by platosha — CHANGES_REQUESTED** [review]

**Review by platosha — APPROVED** [review]
