### PR TITLE
fix: allow using slotted elements in Select

### LINKED ISSUE #131: Can't add child components to a Select
`Select` doesn't allow any child components, such as `<Icon>` or a `<Tooltip>`.

Effectively, [this example](https://vaadin.com/docs/latest/components/select#basic-features) doesn't work in React:

```jsx
<Select label="Label" helperText="Helper text" placeholder="Placeholder" items={items}>
  <Tooltip slot="tooltip" text="Tooltip text" />
  <Icon slot="prefix" icon="vaadin:vaadin-h" />
</Select>
```

### PR DESCRIPTION
**Pull request by web-padawan**
## Description

Fixes #131

Previously, `Select` passed `props.children` to `useSimpleOrChildrenRenderer` as is. This PR changes it so that we get elements with `slot` to be rendered in light DOM, and then evaluate remaining `children` to pass to the hook.

## Type of change

- Bugfix

### CODE REVIEW

File: src/Select.tsx [hunk 1]
```diff
@@ -16,15 +17,41 @@ export * from './generated/Select.js';
...
 function Select(props: SelectProps, ref: ForwardedRef<SelectElement>): ReactElement | null {
+  const children = Children.toArray(props.children as ReactNode[]);
+
+  // Components with slot attribute should stay in light DOM.
+  const slotted = children.filter((child: any) => {
+    return 'props' in child && child.props.slot;
+  });
+
+  // Component without slot attribute should go to the overlay.
+  let overlayChildren: ReactNode[] | undefined;
```
Comment (web-padawan) [inline src/Select.tsx:37]: Note: it is important to not initialize empty array here, as otherwise it would break `items` logic.

File: src/Select.tsx [hunk 2]
```diff
@@ -16,15 +17,41 @@ export * from './generated/Select.js';
...
+      if (!overlayChildren) {
+        overlayChildren = [];
+      }
+      overlayChildren.push(child);
+    }
+  });
+
+  // React.Children.toArray() doesn't allow functions, so we convert manually.
+  const renderFn = (Array.isArray(props.children) ? props.children : [props.children]).find(
+    (child: any) => typeof child === 'function',
```
Comment (tomivirkki) [inline src/Select.tsx:50]: Unnecessary use of `any`

File: src/Select.tsx [hunk 3]
```diff
@@ -16,15 +17,41 @@ export * from './generated/Select.js';
...
+    children?: ReactNode | SelectRenderer | Array<ReactNode | SelectRenderer>;
+    renderer?: SelectRenderer | null;
   }>;
 
 function Select(props: SelectProps, ref: ForwardedRef<SelectElement>): ReactElement | null {
+  const children = Children.toArray(props.children as ReactNode[]);
+
+  // Components with slot attribute should stay in light DOM.
+  const slotted = children.filter((child: any) => {
+    return 'props' in child && child.props.slot;
```
Comment (tomivirkki) [inline src/Select.tsx:33]: This will throw an error if a child is a string. You can fix this and avoid use of `any` with `return typeof child === 'object' && 'props' in child && child.props.slot;`

File: src/Select.tsx [hunk 4]
```diff
@@ -16,15 +17,41 @@ export * from './generated/Select.js';
...
+  let overlayChildren: ReactNode[] | undefined;
+
+  children.forEach((child) => {
+    if (!slotted.includes(child)) {
+      if (!overlayChildren) {
+        overlayChildren = [];
+      }
+      overlayChildren.push(child);
+    }
+  });
```
Comment (tomivirkki) [inline src/Select.tsx:46]: nit: Could simplify this to:
```ts
const overlayChildren = children.filter((child) => !slotted.includes(child));
```

and then pass `renderFn || overlayChildren.length ? overlayChildren : undefined` to the renderer hook

File: src/Select.tsx (hunk 2 above)
Comment (web-padawan) [reply src/Select.tsx]: Removed.

File: src/Select.tsx (hunk 3 above)
Comment (web-padawan) [reply src/Select.tsx]: Thanks, changed.

File: src/Select.tsx (hunk 4 above)
Comment (web-padawan) [reply src/Select.tsx]: Done.

File: src/Select.tsx [hunk 5]
```diff
@@ -16,15 +17,35 @@ export * from './generated/Select.js';
...
 export type SelectProps = Partial<Omit<_SelectProps, 'children' | 'renderer'>> &
   Readonly<{
-    children?: ReactNode | ComponentType<SelectReactRendererProps>;
-    renderer?: ComponentType<SelectReactRendererProps> | null;
+    children?: ReactNode | SelectRenderer | Array<ReactNode | SelectRenderer>;
+    renderer?: SelectRenderer | null;
   }>;
 
 function Select(props: SelectProps, ref: ForwardedRef<SelectElement>): ReactElement | null {
+  const children = Children.toArray(props.children as ReactNode[]);
```
Comment (Lodin) [inline src/Select.tsx:29]: I see a couple of repeating code here and below, at line 40. I guess, it also could fail if children is a `function`.

File: src/Select.tsx [hunk 6]
```diff
@@ -16,15 +17,35 @@ export * from './generated/Select.js';
...
+
+  // Components with slot attribute should stay in light DOM.
+  const slotted = children.filter((child) => {
+    return typeof child === 'object' && 'props' in child && child.props.slot;
```
Comment (Lodin) [inline src/Select.tsx:33]: You can use [React.isValidElement](https://react.dev/reference/react/isValidElement) here.

**Review by Lodin — CHANGES_REQUESTED** [review]
Overall, it looks pretty good to me; however, there is a couple of notes for some error-related stuff.

File: src/Select.tsx (hunk 5 above)
Comment (web-padawan) [reply src/Select.tsx]: Updated to not use `Children.toArray` and only convert `props.children` to array here.

File: src/Select.tsx (hunk 6 above)
Comment (web-padawan) [reply src/Select.tsx]: Thanks, done.

**Review by tomivirkki — DISMISSED** [review]

File: src/Select.tsx [hunk 7]
```diff
@@ -16,15 +17,35 @@ export * from './generated/Select.js';
...
+    children?: ReactNode | SelectRenderer | Array<ReactNode | SelectRenderer>;
+    renderer?: SelectRenderer | null;
   }>;
 
 function Select(props: SelectProps, ref: ForwardedRef<SelectElement>): ReactElement | null {
+  // React.Children.toArray() doesn't allow functions, so we convert manually.
+  const children = Array.isArray(props.children) ? props.children : [props.children];
+
+  // Components with slot attribute should stay in light DOM.
+  const slotted = children.filter((child): child is ReactNode => {
```
[the remark this answers is not in the document]
Comment (web-padawan) [reply src/Select.tsx]: Renamed.

**Review by Lodin — APPROVED** [review]
