### PR TITLE
fix: batch flushSync execution within a microtask

### LINKED ISSUE #255: Maximum update depth exceeded with AutoGrid columnRendering set to lazy
I see this error on AutoGrid. 
Whenever I have `columnRendering` set to `lazy `I see this error. If I change it back to `eager `this error will go away. 

 

> Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn’t have a dependency array, or one of the dependencies changes on every render.
> 
> console.error @ list:5
> r9.error @ useRenderer.ts:60
> printWarning @ react-dom.development.js:86
> error @ react-dom.development.js:60
> checkForNestedUpdates @ react-dom.development.js:27339
> scheduleUpdateOnFiber @ react-dom.development.js:25514
> dispatchReducerAction @ react-dom.development.js:16633
> (anonymous) @ useRenderer.ts:62
> flushSync @ react-dom.development.js:26228
> flushSync$1 @ react-dom.development.js:29878
> (anonymous) @ useRenderer.ts:62
> _runRenderer @ vaadin-grid-column-mixin.js:612
> (anonymous) @ vaadin-grid-column-mixin.js:643
> __renderCellsContent @ vaadin-grid-column-mixin.js:626
> _renderBodyCellsContent @ vaadin-grid-column-mixin.js:709
> _onRendererOrBindingChanged @ vaadin-grid-column-mixin.js:714
> runMethodEffect @ property-effects.js:1038
> runEffects @ property-effects.js:140
> _propertiesChanged @ property-effects.js:1922
> _flushProperties @ properties-changed.js:384
> _invalidateProperties @ property-effects.js:1748
> Object.defineProperty.set @ properties-changed.js:170
> (anonymous) @ vaadin-grid-mixin.js:547
> _createScrollerRows @ vaadin-grid-mixin.js:545
> _createPool @ virtualizer-iron-list-adapter.js:408
> _increasePoolIfNeeded @ iron-list-core.js:434
> _increasePoolIfNeeded @ virtualizer-iron-list-adapter.js:724
> flush @ debounce.js:124
> (anonymous) @ debounce.js:159
> flushDebouncers @ debounce.js:157
> flush @ debounce.js:172
> set size @ virtualizer-iron-list-adapter.js:355
> set size @ virtualizer.js:49
> _flatSizeChanged @ vaadin-grid-mixin.js:300
> runMethodEffect @ property-effects.js:1038
> runEffects @ property-effects.js:140
> _propertiesChanged @ property-effects.js:1922
> _flushProperties @ properties-changed.js:384
> _invalidateProperties @ property-effects.js:1748
> Object.defineProperty.set @ properties-changed.js:170
> _onDataProviderPageReceived @ vaadin-grid-data-provider-mixin.js:348
> _onDataProviderPageReceived @ vaadin-grid-array-da…rovider-mixin.js:45
> callback @ data-provider-controller.js:254
> load @ data-provider.ts:91
> await in load (async)
> __loadCachePage @ data-provider-controller.js:265
> loadFirstPage @ data-provider-controller.js:215
> _ensureFirstPageLoaded @ vaadin-grid-data-provider-mixin.js:440
> _dataProviderChanged @ vaadin-grid-data-provider-mixin.js:426
> runObserverEffect @ property-effects.js:231
> runEffects @ property-effects.js:140
> _propertiesChanged @ property-effects.js:1922
> _flushProperties @ properties-changed.js:384
> _invalidateProperties @ property-effects.js:1748
> Object.defineProperty.set @ properties-changed.js:170
> (anonymous) @ autogrid.tsx:412
> setTimeout (async)
> (anonymous) @ autogrid.tsx:395
> commitHookEffectListMount @ react-dom.development.js:23189
> commitPassiveMountOnFiber @ react-dom.development.js:24965
> commitPassiveMountEffects_complete @ react-dom.development.js:24930
> commitPassiveMountEffects_begin @ react-dom.development.js:24917
> commitPassiveMountEffects @ react-dom.development.js:24905
> flushPassiveEffectsImpl @ react-dom.development.js:27078
> flushPassiveEffects @ react-dom.development.js:27023
> performSyncWorkOnRoot @ react-dom.development.js:26115
> flushSyncCallbacks @ react-dom.development.js:12042
> flushSync @ react-dom.development.js:26240
> flushSync$1 @ react-dom.development.js:29878
> (anonymous) @ useRenderer.ts:62
> _runRenderer @ vaadin-grid-column-mixin.js:612
> (anonymous) @ vaadin-grid-column-mixin.js:643
> __renderCellsContent @ vaadin-grid-column-mixin.js:626
> _renderHeaderCellContent @ vaadin-grid-column-mixin.js:672
> _onHeaderRendererOrBindingChanged @ vaadin-grid-column-mixin.js:680
> runMethodEffect @ property-effects.js:1038
> runEffects @ property-effects.js:140
> _propertiesChanged @ property-effects.js:1922
> _flushProperties @ properties-changed.js:384
> _invalidateProperties @ property-effects.js:1748
> Object.defineProperty.set @ properties-changed.js:170
> (anonymous) @ vaadin-grid-mixin.js:735
> _updateRow @ vaadin-grid-mixin.js:669
> (anonymous) @ vaadin-grid-mixin.js:900
> iterateChildren @ vaadin-grid-helpers.js:26
> _renderColumnTree @ vaadin-grid-mixin.js:899
> _columnTreeChanged @ vaadin-grid-mixin.js:842
> runMethodEffect @ property-effects.js:1038
> runEffects @ property-effects.js:140
> _propertiesChanged @ property-effects.js:1922
> _flushProperties @ properties-changed.js:384
> _invalidateProperties @ property-effects.js:1748
> Object.defineProperty.set @ properties-changed.js:170
> _updateColumnTree @ vaadin-grid-dynamic-columns-mixin.js:112
> (anonymous) @ vaadin-grid-dynamic-columns-mixin.js:94
> (anonymous) @ debounce.js:84
> microtaskFlush @ async.js:35
> (anonymous) @ async.js:179

### PR DESCRIPTION
**Pull request by vursen**
## Description

Simply wrapping renderers in `flushSync` doesn't guarantee that the DOM will be updated synchronously. React may still defer it to a micro task if `flushSync` was called while rendering was already in progress, which is explained in the previously suppressed warning:

> Warning: flushSync was called from inside a lifecycle method. React cannot flush when React is already rendering. Consider moving this call to a scheduler task or micro task.

When there are many deferred sync renderers that in turn trigger some async renderers, it can create race conditions that React misinterprets as a possible infinite loop:

> Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn’t have a dependency array, or one of the dependencies changes on every render.

This warning particularly often occurs in AutoGrid where a mix of sync (GridColumn) and async (Select) renderers is used.

This PR updates Grid renderers to batch `flushSync` execution within a microtask, which resolves the maximum depth warning and is also good for performance. That being said, GridPro's editModeRenderer continues to use unbatched `flushSync` because its web component currently requires the editor to render synchronously.

Fixes #255

## Type of change

- [x] Bugfix

### CODE REVIEW

File: packages/react-components/src/Grid.tsx [hunk 1]
```diff
@@ -19,10 +29,30 @@ function Grid<TItem = GridDefaultItem>(
...
+    innerRef.current!._recalculateColumnWidths = function (...args) {
+      setPendingRecalculateColumnWidthsCall(args);
+    };
+  }, []);
+
+  useEffect(() => {
+    if (pendingRecalculateColumnWidthsCall) {
+      const gridElement = innerRef.current!;
+      const gridProto = Object.getPrototypeOf(gridElement);
+      gridProto._recalculateColumnWidths.call(gridElement, ...pendingRecalculateColumnWidthsCall);
```
Comment (tomivirkki) [inline packages/react-components/src/Grid.tsx:49]: Something isn't working with the `autoWidth` columns recalculation. I changed the Grid example on dev pages to:
```
...
<GridTreeColumn frozen path="name" header="This is a long header" autoWidth flexGrow={0} />
<GridColumn path="name" header="This is a long header" autoWidth flexGrow={0} />
...
```

On `main`:
Screenshot 2024-11-18 at 11 52 41

On the PR branch:
Screenshot 2024-11-18 at 11 52 57

File: packages/react-components/src/Grid.tsx [hunk 2]
```diff
@@ -19,10 +30,30 @@ function Grid<TItem = GridDefaultItem>(
...
 ): ReactElement | null {
-  const [portals, rowDetailsRenderer] = useModelRenderer(props.rowDetailsRenderer, { renderSync: true });
+  const [portals, rowDetailsRenderer] = useModelRenderer(props.rowDetailsRenderer);
+
+  const innerRef = useRef<GridElement & { _recalculateColumnWidths?(...args: any[]): void }>(null);
+  const finalRef = useMergedRefs(innerRef, ref);
+
+  const [pendingRecalculateColumnWidthsCall, setPendingRecalculateColumnWidthsCall] = useState<any[] | null>(null);
+
+  useLayoutEffect(() => {
```
Comment (tomivirkki) [inline packages/react-components/src/Grid.tsx:40]: This change introduces a bit of jumpiness to Grid since the column auto-widths are calculated asynchronously.

https://github.com/user-attachments/assets/eca42b54-d233-40fb-9459-4597715e1a96

File: test/Grid.spec.tsx [hunk 3]
```diff
@@ -374,16 +414,67 @@ describe('Grid', () => {
...
+
+      function doubleClick(element: Element) {
+        element.dispatchEvent(new MouseEvent('dblclick', { bubbles: true }));
+      }
+
+      beforeEach(() => {
+        items = Array.from(new Array(1)).map((_, i) => ({ name: `name-${i}` }));
+      });
+
+      it.only('should update the content', async () => {
```
Comment (tomivirkki) [inline test/Grid.spec.tsx:445]:
```suggestion
      it('should update the content', async () => {
```

File: packages/react-components/package.json [hunk 4]
```diff
@@ -534,4 +538,4 @@
     "./renderers/useSimpleRenderer.js": "./renderers/useSimpleRenderer.js",
     "./renderers/useSimpleRenderer.js.map": "./renderers/useSimpleRenderer.js.map"
   }
-}
\ No newline at end of file
+}
```
Comment (tomivirkki) [inline packages/react-components/package.json:541]: Looks like `npm run build` always reverts this change. Maybe it's better to keep it as it was to avoid unintentional local changes.

Comment (vursen) [reply packages/react-components/package.json]: Done.

File: packages/react-components-pro/src/GridProEditColumn.tsx [hunk 5]
```diff
@@ -61,99 +56,101 @@ export type GridProEditColumnProps<TItem> = Partial<
...
+    };
+  }, []);
+
+  useLayoutEffect(() => {
+    innerRef.current!._renderEditor = function (cell, model) {
+      // Manually clear the cell content only if it was rendered by the default grid renderer.
+      // For content rendered by a React renderer, clearing is handled by removing the portal.
+      if (!bodyRenderer) {
+        this._clearCellContent(cell);
+      }
```
Comment (tomivirkki) [inline packages/react-components-pro/src/GridProEditColumn.tsx:108]: Can you also add a test case for this?

**Review by tomivirkki — APPROVED** [review]
